### PR TITLE
remove router navigation on bundle close (fixes #14)

### LINKED ISSUE #14: Closing the missing bundle modal goes back in history
When no block is found by number, there's a funny modal indicating so.

image

But when you hit `Close`, it goes back to whatever the user had in their history. That's a side effect of closing the modal of a valid bundle and returning to the main screen. And it needs to be fixed.

image

### PR DESCRIPTION
**Pull request by dylankilkenny**
fixes  #14

As far as I can see this resolves the issue and has no additional side effects.

### CODE REVIEW

**Comment by martriay** [comment]
Thanks for doing this! The problem with simply removing that line is that it keeps the blocknumber in the URL when closing an open bundle

* This breaks permalink sharing (if you share your URL at that point it'll point to a specific block)
* It breaks `from` filtering: if you're filtering by a certain `from` address, closing a bundle should return to that filtered list.

**Comment by dylankilkenny** [comment]
ok gotcha this doesnt do then, I didnt realise there is address filtering. Whats the expected behavior of the close button if no bundle has been found ?

**Comment by martriay** [comment]
Just close, no `back`.

This should do it:
```
setOpen(false);
if (bundle) {
  router.back();
}
```

**Comment by martriay** [comment]
Thanks!

**Pull request merged**
